### ISSUE TITLE
using a key Objects and then trying to add :attributes! to it's XML

### ISSUE THREAD

**Issue by bmuscolino** [rubiii/savon#1]
http://stackoverflow.com/questions/12844795/why-savon-attributes-not-working-with-an-object-called-objects

**Comment by rubiii** [comment]
didn't notice this issue. sorry. updating it just in case anyone finds this.
i tried translating your hash using gyoku and it returns the expected result.

``` ruby
Gyoku.xml(
  'Objects' => { 'some' => 'thing' }, 
  :attributes! => { 'Objects' => { 'xsi:type' => 'something' } }
)
```

``` xml
<Objects xsi:type="something"><some>thing</some></Objects>
```

not sure if this has been fixed by now or if i need to test it through savon.
in that case i would need the wsdl for debugging.

if this is still relevant, [please open a new issue here](https://github.com/savonrb/savon).
